momentum-design/tokens

package.json
Update the package name to reflect how it is being published
=> fix(packagename): update package name

components/code-input.json
=> Code input

components/code-input.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json
- Update light and dark common tokens to reflect latest figma design.
- Implement error and disabled states for code input
=> Code input disabled

components/button.json
Update button text token to match design
=> Fix button text colours

components/button.json
=> outline button borders not rendered

components/code-input.json, components/search.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json, theme_generator.js
proposal to add search component + update code-input
@paulwitty
=> Add search

components/banner.json
adding the banner component from here: https://www.figma.com/file/z6oi9Ku3X7rM1Wj2451B9u/Rebrand-Android?node-id=4163%3A22891
@paulwitty
=> add banner

components/button.json, components/label.json, components/text-input.json
Add json for general labels that are used throughout the app
Add text input json (code-input and search should probably be moved to this file in my opinion)
Add missing disabled states to buttons
=> add text-iniput labels and disabled states for certain buttons

components/button.json
Adding new button tokens, but also updated the current button tokens with border tokens for HC support.
=> Add new button tokens

components/avatar.json
update avatar text color to figma spec
=> Fix avatar text color

components/button-group.json, package-lock.json
The scope of the changes in this pull request are to add button-group tokens to the exported CSS tokens.
Build CSS after changes:
=> feat(components/button-group): add tokens

components/share.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json
Add token for share window 
Figma: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows%2BWeb?node-id=9532%3A17790
=> add token for share window

components/button.json, theme_generator.js
=> Add token for layout button

components/banner.json
=> Add transient colours to banner.json

components/alert-badge.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json
=> Alert Badge component

components/combobox.json
[Spec](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows%2BWeb?node-id=4969%3A10093)
=> Add tokens for basic combobox

components/search.json, platformcomponents/desktop/search.json, platformcomponents/mobile/search.json, theme_generator.js
This PR updates the search tokens to use the correct values from the Figma spec.
=> Search token update

platformcomponents/desktop/scrollbar.json
Fix token issue
moved file to platformcomponents desktop
=> Fixed scrollbar token issue and moved file to platformcomponents/desktop

components/interactive-icon.json
=> Add interactive icons tokens

platformcomponents/ios/slider.json
make changes to min and max track tint color for slider on iOS 
add text for disabled state
=> make changes to min and max track tint for ios

platformcomponents/ios/segmentButton.json, theme_generator.js
add segment button tokens for iOS
add console statement for SyntaxErrors on Json files
=> Add segment button

platformcomponents/ios/toolbarButton.json
```
```
Added tokens toolbarButton iOS specific component. [figma](https://www.figma.com/file/L67wWWZaXcvVOLEpn77adE/Components---iOS?node-id=6583%3A66671)
* …
=> added ios toolbar button tokens

platformcomponents/android/button.json
=> {fix}/{android}/{disabled state for ghost}

platformcomponents/desktop/share.json, targets/android.json, targets/ios.json, targets/macos.json, targets/qt.json, targets/web.json, targets/windows-high-contrast.json, theme-data/common/common.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json, theme-data/win-system-hc/win-system-hc-common.json, themes/theme-dark-bronze.json, themes/theme-dark-indigo.json, themes/theme-dark-jade.json, themes/theme-dark-lavender.json, themes/theme-dark-rose.json, themes/theme-dark-webex.json, themes/theme-light-bronze.json, themes/theme-light-indigo.json, themes/theme-light-jade.json, themes/theme-light-lavender.json, themes/theme-light-rose.json, themes/theme-light-webex.json
=> Share tokens

theme-data/dark/dark-common.json, theme-data/light/light-common.json
*This PR updates the component tokens for MomentumAvatar to match the figma spec*
=> {fix}/{avatar}/{update avatar component tokens to match figma spec}

platformcomponents/desktop/globalheader.json
Update device button text in global header
=> update global header device button text tokens

components/list-item.json
Add red color for text of missed call
=> add missed call text color token

platformcomponents/desktop/multiline-chip.json
Add multiline chip tokens
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=2970%3A31
=> Add multiline chip

platformcomponents/desktop/overlay-fade.json, platformcomponents/desktop/panel.json
=> Adding panel and overlay views for desktop

components/tab.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json
=> Tokens for first column tabs

platformcomponents/desktop/tag.json, theme-data/win-system-hc/win-system-hc-common.json
Add tokens for Tags
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=2925%3A17509
=> Add Tag tokens

platformcomponents/desktop/tag.json, theme-data/common/common.json, theme-data/win-system-hc/win-system-hc-common.json
Update overlay button tag after design update
https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=3078%3A6338
=> update tag text and add new common color token

components/avatar.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json, theme-data/win-system-hc/win-system-hc-common.json
=> Chat bubble component.

platformcomponents/desktop/card.json, platformcomponents/desktop/meeting-marker.json
=> Add card component for desktop

components/button.json
=> style: Layout button pressed color

platformcomponents/desktop/interactive-icon.json
Update interactive icons to fix desktop build
=> update interactive tertiary disabled state to fix desktop client

theme-data/win-system-hc/win-system-hc-common.json
=> Windows HC requirements

platformcomponents/desktop/multiline-chip.json
=> Rename border to outline for multiline chips

components/avatar.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json, theme-data/win-system-hc/win-system-hc-common.json
=> Tidy up duplicate of theme-control-active token

targets/windows-high-contrast.json, theme_generator.js
=> Ensure HC theme ignores alpha modifiers

components/list-item.json, platformcomponents/win-hc/button.json, platformcomponents/win-hc/globalheader.json, platformcomponents/win-hc/list-item.json, platformcomponents/win-hc/scrollbar.json, theme-data/win-system-hc/win-system-hc-common.json
=> High Contrast requirements for Windows

components/list-item.json, platformcomponents/win-hc/list-item.json, theme-data/win-system-hc/win-system-hc-common.json
=> Add focus state to Listitem-background

theme_generator.js, themes/theme-win-system-hc-webex.json
=> Update filenames and parent nodes for desktop targets

theme_generator.js
Attempting to debug circle ci issues
=> [Desktop] Replace "active" with "checked" states

theme-data/dark/dark-additional.json, theme-data/light/light-additional.json
=> [SPARK-278700] (Win) Cropped white border on round gray initials avatar

components/meeting-card-list-item.json, platformcomponents/desktop/checkbox.json
Add meeting list card item and fix incorrect checkbox colour
=> Add meeting list background update checkbox border tokens

components/messages.json, platformcomponents/win-hc/messages.json
=> Create dedicated tokens for Messages list

platformcomponents/desktop/list-header.json
Added some of the list-header tokens -- outline
https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=12652%3A3113
=> feat(list-header): add tokens

platformcomponents/desktop/button.json
panel buttons on a call https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=3153%3A216
=> add call control panel button

components/meeting-card-list-item.json, platformcomponents/win-hc/meeting-card-list-item.json
=> High Contrast for HomeTab

platformcomponents/desktop/button.json
Ghost button was missingn disabled state
=> add missing disabled state to ghost button

platformcomponents/win-hc/button.json, theme-data/win-system-hc/win-system-hc-common.json
=> update color token for HC mode

package-lock.json, platformcomponents/desktop/toggle-momentum-style.json, platformcomponents/ios/toggle.json
Adding component tokens for the toggle momentum style.
[*Links to Component Library.*](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=4931%3A1039)
=> feat / add-platform-components / add toggle momentum style tokens

platformcomponents/desktop/share.json, platformcomponents/win-hc/share.json, theme-data/win-system-hc/win-system-hc-common.json
=> Update sharing high contrast tokens

components/badge.json
=> add recording indicator

components/tags.json
The scope of the changes in this pull request are to add the `tags` tokens for web usage.
Note: There is an existing set of tokens that are labeled `tag`, these do not meet web design-spec, and include invalid values for web-based usage.
[SPARK-320559](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-320559)
=> feat(components/tags): add tags web component tokens

platformcomponents/desktop/checkbox.json
update unchecked checkbox border colour to match figma
https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=4371%3A9978
=> update desktop checkbox unchecked border to spec

platformcomponents/win-hc/checkbox.json
=> style/Complete HC checkbox tokens

platformcomponents/desktop/coachmark-teaching.json, platformcomponents/win-hc/coachmark-teaching.json, theme-data/win-system-hc/win-system-hc-common.json
=> Fix coachmark teaching tokens

platformcomponents/desktop/button.json
=> add check status for ghost button

platformcomponents/win-hc/interactive-icon.json
=> Fix interactive icon HC colors

theme-data/common/common.json
=> Fix common active button background colors

platformcomponents/ios/button.json, platformcomponents/ios/text-input.json, themes/ios/theme-light-lavender.json
=> Update accent ghost button iOS only

.circleci/config.yml
Fix circleci docs publishing script.
Added npm i.
=> feat(circleci): add npm i

themes/theme-dark-webex.json, themes/theme-light-webex.json
=> feat(config content-color)

platformcomponents/desktop/video-support.json
Figma link: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=33565%3A54514
=> feat(nameLabel): add mute and unmute icon tokens

components/spinner.json, theme-data/common/common.json
Add common Spinner 
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=14059%3A124985
=> add common spinner

theme-data/common/common.json
=> Fixed bad color reference from common theme

platformcomponents/desktop/meeting-recording.json
PR to add the colours for the recording indicators
=> Recording indicators

platformcomponents/desktop/notification-toast.json
Adding tokens for notification toast
=> feat(notification-toast): add notification toast tokens

platformcomponents/desktop/touchbar.json, theme-data/common/common.json, theme-data/win-system-hc/win-system-hc-common.json
update tokens for touchbar to align with figma design changes
https://www.figma.com/file/uTiF8j59yEbhbT3pgLYgxs/Tokens---Theme-Color---Additional?node-id=1008%3A686
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=15991%3A147675
=> touch bar token updates

platformcomponents/desktop/touchbar.json
fix typo where whiteboard was twice instead of link and whiteboard
=> update touchbar for link

platformcomponents/desktop/date-picker.json
Link: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=44859%3A103117
PR add daye-picker color token
name             	   |  picture
:-------------------------:|:-------------------------:
** **  |  ** screenshot **
date: |![image](https://user-images.githubusercontent.com/107181428/179918119-c7a88f30-f669-4109-b847-0f2a861d6459.png)
day|![image](https://user-images.githubusercontent.com/107181428/179746744-f7b4ff91-5d59-406d-98e3-d570bbc770f8.png)
=> SPARK-346728: DatePicker Color Token added to momentum repo

components/avatar.json
add busy avatar presence indicator
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=3153%3A1008
=> add busy avatar state

platformcomponents/desktop/date-picker.json
https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=44859%3A103117
UI
Original             	   |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **
*![image](https://user-images.githubusercontent.com/107181428/182518199-43c2d8f5-4049-4791-b2d7-a6c14746779b.png)|![image](https://user-images.githubusercontent.com/107181428/182518126-3b79a34b-73bc-4c12-bd12-ab45babc9d9c.png)
=> daypicker compenent update for color token

package-lock.json, platformcomponents/desktop/video-support.json
=> fix color token

platformcomponents/desktop/toggle-button.json
Add component tokens for toggle buttons
[*Links to relevent resources.*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=48160%3A80022)
=> feat(toggle-buttons): add toggle button component tokens

platformcomponents/desktop/toggle-button.json
Forgot to add # to the disabled state in [PR-241](https://github.com/momentum-design/tokens/pull/241)
=> feat(toggle-button): add # in disabled state fix

components/avatar.json, reference-tokens/color-theme-additional.json, theme-data/dark/dark-additional.json, theme-data/light/light-additional.json, theme-data/win-system-hc/win-system-hc-common.json
Add avatar yellow for guest
https://www.figma.com/file/uTiF8j59yEbhbT3pgLYgxs/Tokens---Theme-Color---Additional?node-id=7%3A897
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=6189%3A28049
=> add avatar yellow guest

platformcomponents/desktop/global.json, platformcomponents/win-hc/global.json, platformcomponents/win-hc/label.json
add tokens that were manually added to desktop and were changed on last auto gen
=> add tokens manually added to desktop

components/avatar.json
This PR adds the on-mobile and on-hold tokens for the avatar component
on-mobile -> https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=4594%3A9149
on-hold -> https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=4594%3A9149
=> fix(avatar): add on-hold and on-mobile tokens to avatar

platformcomponents/desktop/participant-list-item.json, platformcomponents/desktop/participant-list.json
```
```
* **message** - add color token of audio state in participant List **REQUIRED** …
=> add color token of audio state in participant List

platformcomponents/desktop/chat-badge.json
=> add badge tokens for messages

components/label.json, theme-data/common/common.json, theme-data/win-system-hc/win-system-hc-common.json
=> add Common-TextWarning-normal token

package.json
The scope of the changes within this Pull Request are to add building of JSON tokens when building for the `web` platform. This will widen the consumption potential of web publishing to allow for styling via JS, or CSS-in-JS flows.
=> feat(package): add json files to npm package

theme-data/common/common.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json, theme-data/win-system-hc/win-system-hc-common.json
Regular audit of core and theme tokens. 
https://www.figma.com/file/n9T5usku57ecvPArT9SpWO/Tokens---Core-Color?node-id=0%3A1
https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=0%3A1
https://www.figma.com/file/uTiF8j59yEbhbT3pgLYgxs/Tokens---Theme-Color---Additional?node-id=1008%3A686
=> feat(audit): audit oct 2022

platformcomponents/desktop/button.json, theme-data/common/common.json, theme-data/win-system-hc/win-system-hc-common.json
=> add common secondary

package.json, scripts/commands/update/update.js, scripts/commands/update/update.test.js, scripts/index.js, scripts/models/color-token/color-token.js, scripts/models/color-token/color-token.test.js, scripts/models/gradient-token/gradient-token.js, scripts/models/gradient-token/gradient-token.test.js, scripts/models/solid-token/solid-token.js, scripts/models/solid-token/solid-token.test.js, scripts/models/token/token.constants.js, yarn.lock
```
```
the core code format is done to read the "new" token format from style dictionary and figma tokens plugin output to the old tokens format so that we can fully move off to the abstract.
* …
=> scripts/tokens/Style Dictionary -> Old Token Format

platformcomponents/ios/text-input.json
=> TextInput/cursor update text input token iOS only

components/links.json
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=2368%3A12504&t=iXlC7pR4IYbStc2i-0
Add differnt link tokens
=> add different link types

theme-data/win-system-hc/win-system-hc-common.json
Changing this so that the color of the text is accessible in comparison to its background color.
=> feat(fix-hc-error-text-color): change from hotlight color to highlightTextColor

components/badge.json
update theme token for warning badge
=> fix warning indicator badge colour token

components/avatar.json, components/button.json
Deleting the referencing to objects and the self-referencing inside component tokens. 
=> feat(tokens): expand component tokens

platformcomponents/desktop/messages.json
=> add a hover color for message header in normal state

platformcomponents/desktop/shortcut-input.json
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=19446%3A508448&t=6RwNZcOJcev8cDMb-0
update component after design update
=> update shortcut tokens after design update

components/badge.json, platformcomponents/win-hc/badge.json, platformcomponents/win-hc/banner.json, platformcomponents/win-hc/button.json, platformcomponents/win-hc/combobox.json, platformcomponents/win-hc/dualbutton.json, platformcomponents/win-hc/interactive-icon.json, platformcomponents/win-hc/links.json, platformcomponents/win-hc/radio.json, platformcomponents/win-hc/scrollbar.json, platformcomponents/win-hc/tag.json, platformcomponents/win-hc/toggle-button.json, theme-data/win-system-hc/win-system-hc-common.json
HC Tokens Update / Badge, Button, CheckBox, Dual Button, Radio Button, ScrollBar, Tags
```
```
* [Getting Started …
=> HC Tokens Update / Badge, Button, CheckBox, Dual Button, Radio Button, ScrollBar, Tags

platformcomponents/desktop/toggle-button-overlay.json, platformcomponents/desktop/toggle-button-solid.json
Figma: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=44859%3A103949&t=GVDamU9otwdv5lMk-0
@nataliadelmar  Can you help me to review this please? Thanks
=> add toggle button solid

platformcomponents/desktop/shortcut-input.json
update background token of shortcut input control
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=19446-508448&t=LTD1FGeDd60CZZCa-0
=> update shorcut input token

platformcomponents/desktop/overlay-fade.json
Add meetings overlay fade token
https://www.figma.com/file/BgaR8XkvKo9JrSvqfRnpka/T43.5--SPARK-334102---Show-CAPTCHA-when-attendees-enter-a-host's-Personal-Room?node-id=2516-51288&t=f5XIVLXvYWEvDyqc-0
=> add meetings overlay fade

platformcomponents/desktop/player-slider.json
=> add tokens for slider component

platformcomponents/desktop/alert-badge.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json
Fix incorrect colour token for default alert badge
Add static alert badge
https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=74238-599861&t=WcLo9AewOa1LL0sT-0
=> Add static badge update colour tokens

platformcomponents/desktop/player-slider.json
=> correct tokens for slider component - track

platformcomponents/desktop/messages.json, platformcomponents/win-hc/list-item.json
Updates to High Contrast tokens (windows)
=> High Contrast Updates - Messaging

platformcomponents/win-hc/list-item.json
High Contrast token fix (list-items)
=> HC token fix

platformcomponents/desktop/attachment-audio.json, platformcomponents/desktop/attachment-ecm.json
=> Ecm no thumbnail tokens

platformcomponents/desktop/attachment-unfurl.json
=> add tokens for unfurl file item

platformcomponents/desktop/overlay-fade.json
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=12675-119003&t=pJMopIjuzvkRIat5-0
Add meetings overlay fade
=> Add meetings reaction overlay

platformcomponents/win-hc/list-item.json
=> Token update

platformcomponents/desktop/welcome-card.json
=> Add color tokens for Welcome cards

platformcomponents/desktop/gradient.json, platformcomponents/win-hc/gradient.json
=> Add new tokens for static gradient background

components/button.json, platformcomponents/desktop/button.json
Add active ghost button and active secondary
=> Add active ghost button and active secondary button

platformcomponents/win-hc/button.json
=> Update the checked state of the buttons in HC mode.

platformcomponents/win-hc/welcome-card.json
=> Update color in HC

platformcomponents/desktop/new-feature-label.json, platformcomponents/win-hc/new-feature-label.json
=> New tokens for discoverability components

platformcomponents/desktop/new-feature-label.json, platformcomponents/win-hc/new-feature-label.json
=> Updates to color token - New Feature lables

components/avatar.json
=> Adding token for reminder avatar colours

platformcomponents/desktop/new-feature-label.json
=> Update to use correct color values - [newFeature] 

components/label.json
=> Add primary inverted label

platformcomponents/desktop/slider.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json, theme-data/win-system-hc/win-system-hc-common.json
=> Create Slider component and update color tokens

platformcomponents/desktop/messages.json
```
```
* **scope** -Migrate reactions to UI toolkit
* **message** - Adding tokens used by reactions **REQUIRED**
* [Contributing Guide](https://github.com/momentum-design/tokens/blob/master/CONTRIBUTING.md) …
=> Add reactions tokens

platformcomponents/win-hc/navigation-bar.json
=> Use windowstext for separator

components/tab.json, platformcomponents/win-hc/tab.json
=> Add new default token and fix more menu (shortcuts, custom and text) in HC

platformcomponents/desktop/messages.json
see https://www.figma.com/file/wMBA6aru0tF19fCU05w5vh/Schedule-Send?node-id=1960%3A371201&mode=dev
=> Tokens for scheduled send header

platformcomponents/desktop/classifications-menu.json
Adding new color tokens for classifications menu component 
```
```
* [Getting Started Guide](https://github.com/momentum-design/tokens/blob/master/GETTING_STAR …
=> Add new tokens for classifications menu

platformcomponents/desktop/meeting-associated-space.json
Adding tokens for Meeting associated space feature. 
```
``` …
=> Add momentum tokens for Meeting Associated space UI

platformcomponents/desktop/classifications-menu.json
=> Update & add classifications tokens

platformcomponents/desktop/messages.json
=> change colors

platformcomponents/desktop/pickup-notification.json
=> [SPARK-467929] [R-1] Update MCW notification to match Figma design - tokens update

platformcomponents/desktop/text-toast-button.json, theme-data/win-system-hc/win-system-hc-common.json
=> Add decline button token

platformcomponents/desktop/indentation-bar.json, platformcomponents/desktop/messages.json
=> add new tokens

platformcomponents/desktop/coachmark-teaching.json
=> update link hover

platformcomponents/desktop/call-history.json, platformcomponents/win-hc/call-history.json
=> add tokens

platformcomponents/desktop/space-bricklet.json
Adding UT tokens for space bricklets following team tab redesign 
```
```
* [Getting Started Guide](https://github.com/momentum-design/tokens/blob/master/GETTIN …
=> add tokens for space bricklet

platformcomponents/desktop/space-bricklet.json
=> add states for background

platformcomponents/desktop/space-bricklet.json
=> team header token 

platformcomponents/desktop/call-history.json, platformcomponents/win-hc/call-history.json
=> update hc tokens

components/spinner.json, package.json, platformcomponents/desktop/slider.json, theme-data/dark/dark-bronze.json, theme-data/dark/dark-indigo.json, theme-data/dark/dark-jade.json, theme-data/dark/dark-lavender.json, theme-data/dark/dark-override.json, theme-data/dark/dark-rose.json, theme-data/light/light-bronze.json, theme-data/light/light-indigo.json, theme-data/light/light-jade.json, theme-data/light/light-lavender.json, theme-data/light/light-override.json, theme-data/light/light-rose.json, theme_generator.js
=> adapte theme core color

components/tags.json, package-lock.json, package.json, platformcomponents/desktop/compose-area.json, platformcomponents/desktop/navigation-bar.json, platformcomponents/desktop/tag.json, theme-data/dark/dark-override.json, theme-data/light/light-override.json, theme-data/win-system-hc/win-system-hc-common.json, theme_generator.js, yarn.lock
=> update momentum token version to 0.0.66

platformcomponents/desktop/call-history.json, platformcomponents/win-hc/call-history.json, theme_generator.js
=> fix HC script

platformcomponents/desktop/share.json
=> update share token

components/theme-thumbnail.json
=> add theme thumbnail

platformcomponents/desktop/radio.json, platformcomponents/win-hc/radio.json
=> fix radio button color

platformcomponents/win-hc/toggle.json
=> fix toggle button for HC

platformcomponents/desktop/multiline-chip.json
=> Update Multiline-Chip colors

components/image-selector.json
=> add imageSelector tokens

platformcomponents/desktop/video-support.json
=> nameLabelToken

components/image-selector.json
=> for image selector

components/banner.json
=> feat: add live icon color for banner

components/label.json
=> add missing label tokens

components/button.json
=> update button json

components/button.json
=> add back message json

package.json, platformcomponents/desktop/button.json, platformcomponents/desktop/video-support.json
=> add missing components; update to 0.3.0

.gitignore, package.json, platformcomponents/desktop/slider.json, platformcomponents/desktop/video-support.json
=> update slider colors

components/text-input.json
=> fix text input color

components/code-input.json, components/search.json, package.json, platformcomponents/desktop/combobox.json
=> update color tokens

package-lock.json, platformcomponents/desktop/checkbox.json, platformcomponents/desktop/radio.json, yarn.lock
=> update checkbox & radio button

components/text-input.json
=> Update text-input for disabled

components/text-input.json
Reverts momentum-design/tokens#380 for masterForDesktop
=> Revert "Update text-input for disabled"
