components/avatar.json
Add missing presence icon bg token used for the circle bg behind the presence icon.
=> feat(avatar): add missing presence icon bg

theme-data/light/light-common.json
@paulwitty I reviewed these values on the theme tokens figma, and found that the hex values of the color shown in the sample for the light theme did not match the color name provided. they are listed as white-alpha values but the actual color is black-alpha values.
=> match name to hex value sample

theme-data/dark/dark-common.json
Outline Cancel Token in dark mode does not match colour in figma. It is currently red 50 but should be red 40
https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=861%3A6638
=> Update outline cancel colour token

platformcomponents/android/checkbox.json, platformcomponents/ios/checkbox.json
I am changing the color of the checkbox for android and ios
* [Contributing Guide](https://github.com/momentum-design/tokens/blob/master/CONTRIBUTING.md)
for android, the color name (theme token) was incorrectly labeled for the appropriate hex value. this change should align the hex values.
for ios, I am fixing something to match figma changes for the background color as well
=> {fix}/{mobile}/{checkbox background color issues}

platformcomponents/desktop/gradient.json
For the new gradient themes desktop is currently unable to use the `theme-background-gradient-xx` tokens due to our parsing logic expecting each token to have at least 1 UI state (`normal`). Today, the tokens being generated from the `gradiation.json` file have no UI state, and get omitted from the generated theme files if we run the script with `--omitThemeTokens`. Looking back through the history of the `Component Tokens dev discussion` space, this particular issue has already come up and the proposed solution at the time was to add additional component files for desktop where needed.
[Figma](https://www.figma.com/file/6Wrt4B7fn41nqSTgFpgwpc/UI-Color-Themes?node-id=9364%3A65784)
Discussion in the `Component Tokens dev discussion` space:
=> feat: add-gradient-component-for-desktop

platformcomponents/ios/text-input.json
This PR removes the `active` state from all text-input components except for iOS, which needs to distinguish between user/system focus.
=> add ios-specific text-input.json

platformcomponents/desktop/interactive-icon.json
spelling mistake in container disabled caused it to generate its own token rather than state of container
=> Fix interactive icon spelling mistake

platformcomponents/desktop/menu-list-background.json
Fix the menu list background css by adding the `#normal` level to the json
Without this the css ended up like:
```css
--menulistbackground-secondary-border-color-0: r;
--menulistbackground-secondary-border-color-1: g;
--menulistbackground-secondary-border-color-2: b;
--menulistbackground-secondary-border-color-3: a;
--menulistbackground-secondary-border-color-4: (;
--menulistbackground-secondary-border-color-5: 2;
--menulistbackground-secondary-border-color-6: 5;
--menulistbackground-secondary-border-color-7: 5;
--menulistbackground-secondary-border-color-8: ,;
--menulistbackground-secondary-border-color-9:  ;
--menulistbackground-secondary-border-color-10: 2;
--menulistbackground-secondary-border-color-11: 5;
--menulistbackground-secondary-border-color-12: 5; …
```
=> fix(menulistbackground): fix menulist background

components/text-input.json
Add back in `active` for the text input that was still in use by the web
=> fix(textinput): put active back in

platformcomponents/desktop/globalheader.json
Update the tokens for the global head device button after discussion with Windows devs
https://www.figma.com/file/4jlvEOttJciN18b4v3GA86/ARCHIVED_Key-Screens%3A-MacOS?node-id=1135%3A11423
=> Update global device header device button tokens

theme-data/dark/dark-common.json, theme-data/light/light-common.json
Update the presence icon colours in light and dark mode. Design changed after user feedback
https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=0%3A1
=> update presence icon colours

platformcomponents/desktop/interactive-icon.json
As discussed with the design team and James Nestor, the interactive-icon component tokens needed these fixes:
1. Each level (primary, secondary, tertiary…) have open icons. So any icon can appear. I changed the name of the tokens for the icon from 'settings/favorite/flag…' to 'primary-filled/primary-outline/secondary-filled/tertiary-filled/etc'?
2. Some colors were wrong. For example, some theme tokens were TextSecondary-normal. Previously, all of them where TextPrimary-normal. 
3. On the tertiary level (the favorite icon), the color the icon gets on active is open to change. With the favorite icon, it should turn yellow, but with another icon, the color could be different. Given we know the color of the active state of the favorite icon only, I added '**favorite**-icon-active' to the …
=> fix: interactive icons component tokens fix

theme-data/dark/dark-common.json, theme-data/light/light-common.json
I've updated the common controls theme tokens for light and dark based on the figma here: https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=861%3A6639 referencing https://www.figma.com/file/n9T5usku57ecvPArT9SpWO/Tokens---Core-Color?node-id=442%3A1 to check the colors.
=> feat(controls): update theme token colors

theme_generator.js
=> [Desktop] Replace "active" with "checked" states

platformcomponents/desktop/text-input.json
=> [Desktop][SPARK-286389]: Fix textinput 'pressed' colour on desktop

components/button.json, theme-data/common/common.json, theme-data/win-system-hc/win-system-hc-common.json
=> Add join meeting animated button color token

components/closed-caption.json, theme-data/common/common.json, theme-data/win-system-hc/win-system-hc-common.json
UX has add the close caption to the library.
https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=40865%3A50204
Add the color token for the control.
Note:
These. color are not change when theme change. 
In each, user can changed the color of the closed caption box
=> add closed caption tokens

theme-data/win-system-hc/win-system-hc-common.json
=> Modify color token for join animated button on win high contrast theme

platformcomponents/desktop/globalheader.json, platformcomponents/desktop/video-support.json
The "none" only works with auto generation on desktop with the "border" type. Update none on other types to use transparent tokens to fix desktop
=> Fix using none token on things that are not borders

platformcomponents/desktop/share.json, theme-data/common/common.json, theme-data/win-system-hc/win-system-hc-common.json
Add missing share button that had been manually added to momentum tokens
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=8109%3A34645
=> add share active button

platformcomponents/win-hc/checkbox.json, theme-data/win-system-hc/win-system-hc-common.json
https://www.figma.com/file/rNpQFybgpgSfTmhLa441V3/Components---Windows-OS-HighContrast?node-id=4371%3A9978
For high contrast mode, there are a total of only 8 kinds of colors. Visual design directly uses those colors such as "@color-hc-SystemColorButtonTextColor" instead of tokens like "@theme-control-active-hover". So I think it is better to define those tokens with their original names, to more intuitively match the design.
=> style/Add checkbox HC tokens

platformcomponents/desktop/video-support.json
=> fix the color token for video support name label

platformcomponents/win-hc/text-input.json
* Fixed TextInput placeholder and border colors in High Contrast mode
| Before                                                                                                                                | After                                                                                                                                |
|---------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------|
| ![Before_HCTextInputDisabled](https://user-images.githubusercontent.com/621738/175069427-a64b5aaa-b94a-4ad6-b25a-f884995c254a.png)    | …
=> feat: fix TextInput placeholder and border colors in High Contrast mode

platformcomponents/desktop/touchbar.json, theme-data/common/common.json, theme-data/win-system-hc/win-system-hc-common.json
Add colour tokens for touch bar on mac
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=15991%3A144836
https://www.figma.com/file/uTiF8j59yEbhbT3pgLYgxs/Tokens---Theme-Color---Additional?node-id=1302%3A979
=> add touch bar tokens mac

theme-data/light/light-common.json
=> Fix text secondary inverted token for light mode

platformcomponents/desktop/interactive-icon.json, platformcomponents/win-hc/interactive-icon.json
Favourite icon requires different fill colour when selected in high contrast mode on windows.
Also borders were missing from interactive-icons in high contrast mode.
https://www.figma.com/file/rNpQFybgpgSfTmhLa441V3/Components---Windows-OS-HighContrast?node-id=18590%3A37844
=> fix(win-hc): Use correct colours and add borders for interactive-icons

platformcomponents/desktop/interactive-icon.json, platformcomponents/win-hc/interactive-icon.json
High contrast borders are consistent across all buttons, no need for specific addition to interactive-icons
=> fix(win-hc):remove un-needed borders for interactive-icons

platformcomponents/win-hc/text-input.json
Background was the same colour as text rendering it invisible.
=> fix(win-hc): User correct hover background color for text input

platformcomponents/desktop/toggle-button-accent.json
When toggle buttons have an accent color on its selected state, they have a different set of colours accross their states (normal, hover, pressed, disabled). That is why a separate component for this has been created in this PR.
[*Links to relevent resources.*](https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=46549%3A102963)
=> feat(button-toggle-accent): add button toggle accent comp tokens

platformcomponents/desktop/toggle-button-accent.json
Name fix for ToggleButtonAccent component tokens.
=> feat(toggle-button-accent-name): fix name

platformcomponents/desktop/toggle-button-accent.json
The Momentum Design team updated the active colours of the buttonToggleAccent.
Component in Figma
[*Links to relevent resources.*](https://www.figma.com/file/vdL18BATeJAIq2JvGAjRPD/Components---Web?node-id=49900%3A96263)
=> feat(button-toggle-accent): update active tokens

theme-data/win-system-hc/win-system-hc-common.json
Fix HC text warning color as specified here:
https://www.figma.com/file/rNpQFybgpgSfTmhLa441V3/Components---Windows-OS-HighContrast?node-id=20219%3A149636
=> feat(hc-message-header): change text warning color

platformcomponents/desktop/messages.json
```
```
Needed a color token to be added specifically for the header of the message as we currently have of just the message body. 
* [Getting Started …
=> color token for message header 

components/badge.json
Tokens for new badge types added
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?node-id=2925%3A17742&t=dwSXADFZEq3WbvJs-0
=> Add badge tokens for secondary and warning

platformcomponents/win-hc/messages.json
=> add hc hover color for message header on hover/focus states

core/color/partners.json, platformcomponents/desktop/attachment-file-branded.json, theme-data/common/common.json, theme-data/win-system-hc/win-system-hc-common.json
```
```
Adding new tokens to support "partner" colours for file bricklet attachments (word, excel, PDF, etc). …
=> Adding partner colours (word, pdf, onenote, etc) for file content attachments

platformcomponents/win-hc/shortcut-input.json
Overrides the default colour tokens for the shortcut-input component in high contrast.
=> High contrast tokens update for shortcut input components

theme-data/common/common.json, theme-data/dark/dark-common.json, theme-data/light/light-common.json, theme-data/win-system-hc/win-system-hc-common.json
Updating some theme tokens with latest value according to Figma
https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=861-6638&t=6rWdTSCboEVpeu1a-0
CHANGES MADE:
Common
• [Common-BackgroundAlertShare-normal](https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=3078%3A6338&t=1E4LU4xGkXIcrQwL-1)
Dark / Light both (Links direct to dark)
• [BackgroundReaction-normal](https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=861%3A6638&t=1E4LU4xGkXIcrQwL-1)
• [OverlayMeetingsReaction-normal](https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=861%3A6638&t=1E4LU4xGkXIcrQwL-1)
• [OutlineWarning-normal](https://www.figma.com/file/yYfvFEEr3UkW1yUKkW7zEH/Tokens---Theme-Color?node-id=861%3A6638&t=1E4LU4 …
=> feat(update-tokens): update theme tokens with latest Figma

platformcomponents/desktop/messages.json
Adds token for message overlay background colours.
https://www.figma.com/file/H19CutixoN8SJGO5EXwcc8/Components---MacOS?type=design&node-id=3597%3A582&t=zEnIRgn4AIfBQRgM-1
=> Add token for message overlay background

components/dualbutton.json, platformcomponents/win-hc/dualbutton.json
=> Add disable token in dualbutton
